### ISSUE TITLE
Reporte de práctica 

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-3-practica-architect-Irvingzr16#1]
[FIS Irving Zárate Reyes.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Irvingzr16/files/12544237/FIS.Irving.Zarate.Reyes.pdf)

**Comment by MAB288** [comment]
14.7/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
